/*
 * Copyright 2026 ALE International
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
 * to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 * BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * `AgentByPilotAttributes` defines the set of statistical attributes available
 * for a CCD agent with respect to a specific CCD pilot.
 *
 * These attributes are used in reports generated by `CallCenterStatisticsService`
 * to provide insight into agent performance and activity per pilot.
 *
 * Attributes are grouped into:
 * - **Counts** - number of calls received, served, transferred, etc.
 * - **Durations** - total and average times.
 *
 * **Note:** The `ALL` attribute is intended for testing only and should
 * not be used in production contexts.
 *
 * @since 2.7.4
 */
export enum StatsAgentByPilotAttributes {
    /** Number of calls received for this pilot. */
    nbCallsReceived = 'nbCallsReceived',

    /** Number of calls received by transfer. */
    nbCallsTransfIn = 'nbCallsTransfIn',

    /** Number of calls served. */
    nbCallsServed = 'nbCallsServed',

    /** Number of calls served too quickly. */
    nbCallsServedTooQuickly = 'nbCallsServedTooQuickly',

    /** Number of calls with enquiry. */
    nbCallsWithEnquiry = 'nbCallsWithEnquiry',

    /** Number of calls where help was requested. */
    nbCallsWithHelp = 'nbCallsWithHelp',

    /** Number of calls transferred from the agent. */
    nbCallsTransf = 'nbCallsTransf',

    /** Number of calls transferred to the agent. */
    nbCallsTransfToAgent = 'nbCallsTransfToAgent',

    /** Number of calls in wrap-up. */
    nbCallsInWrapup = 'nbCallsInWrapup',

    /** Maximum duration of call processing (hh:mm:ss). */
    maxCallProcDur = 'maxCallProcDur',

    /** Maximum duration of conversation (hh:mm:ss). */
    maxConvDur = 'maxConvDur',

    /** Maximum duration of wrap-up (hh:mm:ss). */
    maxWrapupDur = 'maxWrapupDur',

    /** Total duration of call processing (hh:mm:ss). */
    callProcTDur = 'callProcTDur',

    /** Average duration of call processing (hh:mm:ss). */
    callProcADur = 'callProcADur',

    /** Total duration of conversation (hh:mm:ss). */
    convTDur = 'convTDur',

    /** Average duration of conversation (hh:mm:ss). */
    convADur = 'convADur',

    /** Total duration of wrap-up (hh:mm:ss). */
    wrapupTDur = 'wrapupTDur',

    /** Average duration of wrap-up (hh:mm:ss). */
    wrapupADur = 'wrapupADur',

    /** Total duration of conversation occurring during wrap-up (hh:mm:ss). */
    convInWrapupTDur = 'convInWrapupTDur',

    /** Total busy time during wrap-up (hh:mm:ss). */
    busyTimeInWrapupTDur = 'busyTimeInWrapupTDur',

    /** Total duration of calls on hold (hh:mm:ss). */
    onHoldTDur = 'onHoldTDur',

    /** Average duration of calls on hold (hh:mm:ss). */
    onHoldADur = 'onHoldADur',

    /** Total duration of transaction phase (hh:mm:ss). */
    transTDur = 'transTDur',

    /** Average duration of transaction phase (hh:mm:ss). */
    transADur = 'transADur',

    /** Total duration of pause (hh:mm:ss). */
    pauseTDur = 'pauseTDur',

    /** Average duration of pause (hh:mm:ss). */
    pauseADur = 'pauseADur',

    /** All attributes (for testing purposes only; not for production use). */
    ALL = 'ALL',
}
