/*
 * Copyright 2026 ALE International
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
 * to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 * BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * `AgentAttributes` defines the set of statistical attributes available
 * for a CCD agent.
 *
 * These attributes are used in reports generated by
 * `CallCenterStatisticsService` to provide insight into agent activity,
 * performance, and call handling.
 *
 * Attributes are grouped into:
 * - **Counts** - number of calls, pickups, refusals, etc.
 * - **Durations** - total and average times, expressed in `hh:mm:ss`.
 * - **Percentages** - proportion of time spent in various agent states.
 *
 * **Note:** The `ALL` attribute is intended for testing only and
 * should not be used in production contexts.
 *
 * @since 2.7.4
 */
export enum StatsAgentAttributes {
    /** Number of rotating timeouts experienced by the agent. */
    nbRotating = 'nbRotating',

    /** Number of calls successfully answered by the agent. */
    nbPickedUp = 'nbPickedUp',

    /** Number of call pickup actions initiated by the agent. */
    nbPickup = 'nbPickup',

    /** Number of internal outgoing calls not associated with ACD. */
    nbLocalOutNonAcd = 'nbLocalOutNonAcd',

    /** Number of external outgoing calls not associated with ACD. */
    // @SerializedName("nbExtOutNonacd")
    nbExtOutNonAcd = 'nbExtOutNonacd',

    /** Number of ACD calls that were presented (rang) to the agent. */
    nbRingAcd = 'nbRingAcd',

    /** Number of calls during which the agent initiated a help request. */
    nbHelp = 'nbHelp',

    /** Number of internal incoming calls not associated with ACD. */
    // @SerializedName("nbLocInNonacd")
    nbLocInNonAcd = 'nbLocInNonacd',

    /** Number of non-ACD external incoming calls received directly. */
    // @SerializedName("nbExtInNonacdDirect")
    nbExtInNonAcdDirect = 'nbExtInNonacdDirect',

    /** Number of non-ACD external incoming calls transferred to the agent. */
    // @SerializedName("nbExtInNonacdTransferred")
    nbExtInNonAcdTransferred = 'nbExtInNonacdTransferred',

    /** Number of ACD calls handled (served) without an associated transaction code. */
    nbServedWOCode = 'nbServedWOCode',

    /** Number of ACD calls handled (served) with an associated transaction code. */
    nbServedWCode = 'nbServedWCode',

    /** Number of ACD calls served too quickly. */
    nbAcdQuickServed = 'nbAcdQuickServed',

    /** Number of non-ACD external incoming calls successfully served. */
    // @SerializedName("nbExtinNonacdServed")
    nbExtInNonAcdServed = 'nbExtinNonacdServed',

    /** Number of non-ACD external incoming calls served too quickly. */
    // @SerializedName("nbExtinNonacdQuickServed")
    nbExtInNonAcdQuickServed = 'nbExtinNonacdQuickServed',

    /** Number of outgoing ACD calls initiated by the agent. */
    nbOutAcd = 'nbOutAcd',

    /** Number of outgoing ACD calls that were answered by the destination party. */
    nbOutAcdAnswered = 'nbOutAcdAnswered',

    /** Number of calls currently or cumulatively in the wrap-up state. */
    nbOnWrapup = 'nbOnWrapup',

    /** Total ringing duration for ACD calls that were served. */
    ringAcdServedTDur = 'ringAcdServedTDur',

    /** Average ringing duration for ACD calls that were served. */
    ringAcdServedADur = 'ringAcdServedADur',

    /** Total ringing duration for non-ACD external incoming calls that were served. */
    ringInNonAcdExtServedTDur = 'ringInNonAcdExtServedTDur',

    /** Average ringing duration for non-ACD external incoming calls that were served. */
    ringInNonAcdExtServedADur = 'ringInNonAcdExtServedADur',

    /** Total ringing duration for ACD calls. */
    ringAcdTDur = 'ringAcdTDur',

    /** Average ringing duration for ACD calls. */
    ringAcdADur = 'ringAcdADur',

    /** Total ringing duration for non-ACD external incoming calls. */
    ringInNonAcdExtTDur = 'ringInNonAcdExtTDur',

    /** Average ringing duration for non-ACD external incoming calls. */
    ringInNonAcdExtADur = 'ringInNonAcdExtADur',

    /** Total ringing duration for all calls. */
    ringTDur = 'ringTDur',

    /** Average ringing duration for all calls. */
    ringADur = 'ringADur',

    /** Total conversation duration for ACD calls. */
    convAcdTDur = 'convAcdTDur',

    /** Average conversation duration for ACD calls. */
    convAcdADur = 'convAcdADur',

    /** Total wrap-up duration for all calls served. */
    wrapupAcdTDur = 'wrapupAcdTDur',

    /** Total conversation duration for internal outgoing non-ACD calls. */
    // @SerializedName("convLocOutNonacdTDur")
    convLocOutNonAcdTDur = 'convLocOutNonacdTDur',

    /** Average conversation duration for internal outgoing non-ACD calls. */
    // @SerializedName("convLocOutNonacdADur")
    convLocOutNonAcdADur = 'convLocOutNonacdADur',

    /**
     * Total conversation duration for external outgoing calls.
     */
    convExtOutTDur = 'convExtOutTDur',

    /**
     * Average conversation duration for external outgoing calls.
     */
    convExtOutADur = 'convExtOutADur',

    /**
     * Total conversation duration for non-ACD internal incoming calls.
     */
    // @SerializedName("convLocInNonacdTDur")
    convLocInNonAcdTDur = 'convLocInNonacdTDur',

    /**
     * Average conversation duration for non-ACD internal incoming calls.
     */
    // @SerializedName("convLocInNonacdADur")
    convLocInNonAcdADur = 'convLocInNonacdADur',

    /**
     * Total conversation duration for non-ACD external incoming calls.
     */
    // @SerializedName("convExtInNonacdTDur")
    convExtInNonAcdTDur = 'convExtInNonacdTDur',

    /**
     * Average conversation duration for non-ACD external incoming calls.
     */
    // @SerializedName("convExtInNonacdADur")
    convExtInNonAcdADur = 'convExtInNonacdADur',

    /**
     * Total call processing duration for outgoing ACD calls.
     */
    outAcdCommTDur = 'outAcdCommTDur',

    /**
     * Average call processing duration for outgoing ACD calls.
     */
    outAcdCommADur = 'outAcdCommADur',

    /**
     * Total conversation duration for outgoing ACD calls.
     */
    outAcdConvTDur = 'outAcdConvTDur',

    /**
     * Average conversation duration for outgoing ACD calls.
     */
    outAcdConvADur = 'outAcdConvADur',

    /**
     * Total transaction phase duration for outgoing ACD calls.
     */
    outAcdTransactTDur = 'outAcdTransactTDur',

    /**
     * Average transaction phase duration for outgoing ACD calls.
     */
    outAcdTransactADur = 'outAcdTransactADur',

    /**
     * Total wrap-up duration for outgoing ACD calls.
     */
    outAcdWrapupTDur = 'outAcdWrapupTDur',

    /**
     * Average wrap-up duration for outgoing ACD calls.
     */
    outAcdWrapupADur = 'outAcdWrapupADur',

    /**
     * Total pause duration for outgoing ACD calls.
     */
    outAcdPauseTDur = 'outAcdPauseTDur',

    /**
     * Average pause duration for outgoing ACD calls.
     */
    outAcdPauseADur = 'outAcdPauseADur',

    /**
     * Total wrap-up duration while the agent was idle.
     */
    wrapUpIdleTDur = 'wrapUpIdleTDur',

    /**
     * Total conversation duration during wrap-up.
     */
    callOnWrapupTDur = 'callOnWrapupTDur',

    /**
     * Total busy time during wrap-up.
     */
    busyOnWrapupTDur = 'busyOnWrapupTDur',

    /**
     * Total busy time for the agent.
     */
    busyTDur = 'busyTDur',

    /**
     * Percentage of total time the agent was logged out.
     */
    loggedOutPerTime = 'loggedOutPerTime',

    /**
     * Percentage of time the agent was logged in but not assigned to a call.
     */
    notAssignedPerTime = 'notAssignedPerTime',

    /**
     * Percentage of time the agent was logged in and assigned to a call.
     */
    assignedPerTime = 'assignedPerTime',

    /**
     * Percentage of time the agent was in withdrawal (unavailable for calls).
     */
    withdrawPerTime = 'withdrawPerTime',

    /**
     * Percentage of time the agent was in withdrawal due to cause 1.
     */
    withdrawPerTimeCause1 = 'withdrawPerTimeCause1',

    /**
     * Percentage of time the agent was in withdrawal due to cause 2.
     */
    withdrawPerTimeCause2 = 'withdrawPerTimeCause2',

    /**
     * Percentage of time the agent was in withdrawal due to cause 3.
     */
    withdrawPerTimeCause3 = 'withdrawPerTimeCause3',

    /**
     * Percentage of time the agent was in withdrawal due to cause 4.
     */
    withdrawPerTimeCause4 = 'withdrawPerTimeCause4',

    /**
     * Percentage of time the agent was in withdrawal due to cause 5.
     */
    withdrawPerTimeCause5 = 'withdrawPerTimeCause5',

    /**
     * Percentage of time the agent was in withdrawal due to cause 6.
     */
    withdrawPerTimeCause6 = 'withdrawPerTimeCause6',

    /**
     * Percentage of time the agent was in withdrawal due to cause 7.
     */
    withdrawPerTimeCause7 = 'withdrawPerTimeCause7',

    /**
     * Percentage of time the agent was in withdrawal due to cause 8.
     */
    withdrawPerTimeCause8 = 'withdrawPerTimeCause8',

    /**
     * Percentage of time the agent was in withdrawal due to cause 9.
     */
    withdrawPerTimeCause9 = 'withdrawPerTimeCause9',

    /**
     * Number of pilots the agent served calls for.
     */
    nbPilots = 'nbPilots',

    /**
     * Number of ACD calls served by the agent.
     */
    nbAcdServedCalls = 'nbAcdServedCalls',

    /**
     * Number of incoming ACD calls served by the agent.
     */
    nbAcdInServedCalls = 'nbAcdInServedCalls',

    /**
     * Number of incoming calls received directly by the pilot and served.
     */
    nbInCallsReceivedByPilot = 'nbInCallsReceivedByPilot',

    /**
     * Number of outgoing ACD calls served by the agent.
     */
    nbAcdOutServedCalls = 'nbAcdOutServedCalls',

    /**
     * Total number of ACD calls not served by the agent.
     */
    nbTotNonServedCalls = 'nbTotNonServedCalls',

    /**
     * Number of incoming ACD calls not served by the agent.
     */
    nbInNonServedCalls = 'nbInNonServedCalls',

    /**
     * Number of incoming ACD calls picked up but not served.
     */
    // @SerializedName("nbPickedupCalls")
    nbPickedUpCalls = 'nbPickedupCalls',

    /**
     * Number of incoming ACD calls refused by the agent.
     */
    nbRefusedCalls = 'nbRefusedCalls',

    /**
     * Number of outgoing ACD calls not served by the agent.
     */
    nbAcdOutNonServedCalls = 'nbAcdOutNonServedCalls',

    /**
     * Total number of non-ACD calls received by the agent.
     */
    // @SerializedName("nbTotNonAcdreceivedCalls")
    nbTotNonAcdReceivedCalls = 'nbTotNonAcdreceivedCalls',

    /**
     * Number of incoming non-ACD calls received by the agent.
     */
    nbInNonAcdCalls = 'nbInNonAcdCalls',

    /**
     * Number of outgoing non-ACD calls initiated by the agent.
     */
    nbOutNonAcdCalls = 'nbOutNonAcdCalls',

    /**
     * Duration the agent was assigned to a group but not in withdrawal.
     */
    assignedNotWithdrawDur = 'assignedNotWithdrawDur',

    /**
     * Total duration the agent was in withdrawal.
     */
    withdrawDur = 'withdrawDur',

    /**
     * Duration the agent spent in manual wrap-up.
     */
    manuWrapupDur = 'manuWrapupDur',

    /**
     * Duration the agent was in an unreachable state.
     */
    unreachableDur = 'unreachableDur',

    /**
     * Total duration spent in non-ACD work.
     */
    nonAcdWorkTDur = 'nonAcdWorkTDur',

    /**
     * Average duration spent in non-ACD work.
     */
    nonAcdWorkADur = 'nonAcdWorkADur',

    /**
     * Total duration spent in ACD work.
     */
    acdWorkTDur = 'acdWorkTDur',

    /**
     * Average duration spent in ACD work.
     */
    acdWorkADur = 'acdWorkADur',

    /**
     * Total duration spent in incoming ACD work.
     */
    acdWorkInTDur = 'acdWorkInTDur',

    /**
     * Average duration spent in incoming ACD work.
     */
    acdWorkInADur = 'acdWorkInADur',

    /**
     * Total conversation duration in incoming ACD work.
     */
    acdWorkInConvTDur = 'acdWorkInConvTDur',

    /**
     * Average conversation duration in incoming ACD work.
     */
    acdWorkInConvADur = 'acdWorkInConvADur',

    /**
     * Total ringing duration in incoming ACD work.
     */
    acdWorkInRingTDur = 'acdWorkInRingTDur',

    /**
     * Average ringing duration in incoming ACD work.
     */
    acdWorkInRingADur = 'acdWorkInRingADur',

    /**
     * Total wrap-up duration in incoming ACD work.
     */
    acdWorkInWrapupTDur = 'acdWorkInWrapupTDur',

    /**
     * Average wrap-up duration in incoming ACD work.
     */
    acdWorkInWrapupADur = 'acdWorkInWrapupADur',

    /**
     * Total duration spent in outgoing ACD work.
     */
    acdWorkOutTDur = 'acdWorkOutTDur',

    /**
     * Average duration spent in outgoing ACD work.
     */
    acdWorkOutADur = 'acdWorkOutADur',

    /**
     * Total conversation duration in outgoing ACD work.
     */
    acdWorkOutConvTDur = 'acdWorkOutConvTDur',

    /**
     * Average conversation duration in outgoing ACD work.
     */
    acdWorkOutConvADur = 'acdWorkOutConvADur',

    /**
     * Total wrap-up duration in outgoing ACD work.
     */
    acdWorkOutWrapupTDur = 'acdWorkOutWrapupTDur',

    /**
     * Average wrap-up duration in outgoing ACD work.
     */
    acdWorkOutWrapupADur = 'acdWorkOutWrapupADur',

    /**
     * Total conversation duration for incoming ACD calls.
     */
    acdInConvTDur = 'acdInConvTDur',

    /**
     * Average conversation duration for incoming ACD calls.
     */
    acdInConvADur = 'acdInConvADur',

    /**
     * Total conversation duration for outgoing ACD calls.
     */
    acdOutConvTDur = 'acdOutConvTDur',

    /**
     * Average conversation duration for outgoing ACD calls.
     */
    acdOutConvADur = 'acdOutConvADur',

    /** All attributes (test purposes only; not for production use). */
    ALL = 'ALL',
}
